### ISSUE TITLE
Looks huge in 1080

### ISSUE THREAD

**Issue by ThatJohn** [Litarvan/lightdm-webkit-theme-litarvan#78] opened 2020-01-27 21:42 UTC
It used to look fine, but I think the changes to accomodate for 4k screen made things look huge in 1080 screens.

**Comment by soanvig** [comment] 2020-02-08 18:41
Please note the version you are using (manually build newest, or stable 3.0.0)

**Comment by Litarvan** [comment] 2020-02-28 15:08
Didn't manage to reproduce on a 1080p screen, can you try sending a picture of what it looks like ?

**Comment by Litarvan** [comment] 2020-02-28 22:15
@RononDex was able to reproduce a similar glitch, I fixed it so i'm closing this for now, feel free to reopen if the issue is still there on the 3.1.0

**Closed by Litarvan** 2020-02-28 22:15 UTC
