### ISSUE TITLE
black vertical line in login prompt mode

### ISSUE THREAD

**Issue by pakro** [Litarvan/lightdm-webkit-theme-litarvan#83] opened 2020-03-13 20:48 UTC
Hi,

when switching from clear visible background image to blurry background image with login prompt after either pressing enter or space a black vertical line is added to the blurry image. This line remains until login is completed.

I've downloaded the source code and tried to reproduce this on the live demo. It is not reproducible in my browser. 

I somehow have the feeling that it is connected to the way the background is blurred, because when I actually use it on my system I see that the line is building up when the blur is fading in and it is deconstructing when I hit escape and leaving the login prompt mode.

Maybe it is somehow connected to the resolution of the monitor and the resolution of the image.

I have a 2560x1440 Monitor. The image itself itself has the same size. But I don't think it is the image itself as other images have the same problem.

![20200313_215206](https://user-images.githubusercontent.com/8904139/76659111-d8236a00-6575-11ea-8573-90e452446eba.jpg)

**Comment by FFY00** [comment] 2020-03-14 19:30
Duplicate of #73.

**Comment by Litarvan** [comment] 2020-03-14 22:11
Are you using the last version ? (3.1.0)

**Comment by pakro** [comment] 2020-03-15 17:34
> Are you using the last version ? (3.1.0)

Nope... I'm on Arch and installed it from AUR. According to the AUR package the version I have installed is 3.0.0-1. I will contact the AUR package maintainer. I will report back as soon as I somehow get the newer version installed. Thank you in advance!

**Comment by Litarvan** [comment] 2020-03-15 17:47
This _should_ have been fixed in 3.1.0, can you try installing it manually from the releases page ? There may be a lagging glitch, i would like to know if that affects you too

**Comment by pakro** [comment] 2020-03-15 17:48
> This _should_ have been fixed in 3.1.0, can you try installing it manually from the releases page ? There may be a lagging glitch, i would like to know if that affects you too

I messed it up I think. I had the community package installed which is not the latest one. I know have installed the git postfixed one and will report back in an instant.

**Comment by pakro** [comment] 2020-03-15 18:01
OK with the new version it is still there but it disappears as soon as the the blur animation is finished. I try to upload a video.


[20200315_185617.mp4.zip](https://github.com/Litarvan/lightdm-webkit-theme-litarvan/files/4334722/20200315_185617.mp4.zip)

**Comment by Litarvan** [comment] 2020-03-15 20:33
I hate GTK Webkit so much :'( this is so hard to debug, and I don't even know if there is a fix that doesn't break everything like it does currently

I'll do my best to find a solution

**Comment by pakro** [comment] 2020-03-15 20:38
I have created a pull request https://github.com/Litarvan/lightdm-webkit-theme-litarvan/pull/85. In my opinion there are two unnecessary properties. Deleting them does not affect the way your stuff works and your design intention (at least I do not see any difference) but it solves the problem for me. Maybe this helps you in finding a better solution! Nobody likes Webkit! :)

**Comment by Litarvan** [comment] 2020-03-15 20:40
:o Are you sure this keeps the blur effect and its transition?

**Comment by Litarvan** [comment] 2020-03-15 20:44
Also, could you test this in "real conditions" ? I mean in LightDM for real (launching lightdm-webkit2-greeter from the terminal is not enough), to see if there is no lag/glitch (because it does this to a lot of people)

**Comment by pakro** [comment] 2020-03-15 20:54
I am testing it currently on my system by really locking and unlocking my system. I reverted the change and the issue is there. I remove those properties like in the pull request and the issue is gone for me. I don't think blur(0px) is the problem (this one is just really unnecessary as you conditionally add the class blurred. And if the condition is not met nothing the blur will be reverted -- you don't need to do that manually twice. I think the transition is the problem but I also don't grasp the intention of it to be honest. Did you add the transition so that the transition from the os logo to the background is looking properly?

**Comment by pakro** [comment] 2020-03-15 20:59
Ahh I believe I now get it... the background is used to fade out after the login is successfully. By removing it the background is stuck until you press a button. Which somehow sucks too.

**Comment by pakro** [comment] 2020-03-15 21:06
I closed the pull request. The transition is important for after the login is successful to somehow show the desktop. Without the transition nothing happens and you need to click to see the desktop. I will see if I find a solution that actually solves the problem without breaking other things. A good time to learn vue.js!

**Comment by pakro** [comment] 2020-03-16 18:10
So I tried around and it is the following line:

`transition: filter 500ms ease-in-out;`

in **base.vue**.

It seems Webkit does not like mixing the transition property with blur filter. Just removing this single line solves the problem on my machine (real testing with lightdm-webkit2-greeter). Also this does not break the forwarding functionality after successfully login like my previous pull request.

In developer mode (npm run serve) I personally don't even see any difference between having the CSS line above or not. But maybe I'm wrong here. 

I've created another pull request. Feel free to accept it, if you ran your test sessions. You can implement it for yourself if you want to, because I also removed additional CSS stuff which I don't think is necessary. I will stick with my solution.

I also want to mention that I see Navigation Duplicated Errors in the console (uncaught exceptions) while working on this solution. Normally exceptions shouldn't be visible in the console.

**Comment by Litarvan** [comment] 2021-04-20 11:10
I added a 'blur settings' view on the 3.2.0 (accessible from the setup screen), from there you should be able to select a different blur method, disable the transition, or even disable the blur.
This should fix your issue or at least provide the best workaround for it.

(I also fixed the navigation dupliated errors in the console :))

**Closed by Litarvan** 2021-04-20 11:10 UTC
